# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sam's Missives
description: >- # this means to ignore newlines until "baseurl:"
  The name's Samuel. I'm a psychology graduate and cyber security master's student. I love films, reading fiction, PC gaming, playing the drums, and doing a little coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samuellucas.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: samuel-lucas6

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: dark
  header_pages:
    - projects.md
    - keys.md
    - contact.md

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
